name: Deploy

on:
  push:
    branches:
      - main

env:
  DEPLOY_DIR: ./public
  DEPLOY_S3_BUCKET: simpleircclient.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Deploy
        run: |
          npm ci
          npx tailwindcss -i ./public/app.css -o ./public/css/style.css
          aws s3 sync $DEPLOY_DIR s3://$DEPLOY_S3_BUCKET --acl public-read
